### ISSUE TITLE
pillow-simd Dead ? 

### ISSUE THREAD

**Issue by JexPY** [uploadcare/pillow-simd#103]
Sorry to bother you @homm, but is this project dead?

**Comment by homm** [comment]
For one who curious: https://github.com/python-pillow/Pillow/issues/5791#issuecomment-965079319

**Comment by homm** [comment]
Versions `8.2.0.post0`, `8.3.2.post0` and `8.4.0.post0` released.

**Comment by JexPY** [comment]
> Versions `8.2.0.post0`, `8.3.2.post0` and `8.4.0.post0` released.

Thanks for finding time to contribute in pillow simd it really deserves to be worked on ✌️

**Comment by qhaas** [comment]
`committed on Sep 23, 2024`
Guess the Project is dead now :(
