### ISSUE TITLE
Clarification: would it be safe to recommend pillow-simd?

### ISSUE THREAD

**Issue by jarun** [uploadcare/pillow-simd#11]
Hi,

Author of [imgp](https://github.com/jarun/imgp) here. I came across `pillow-simd` while looking for a performance benchmark of ImageMagick against Pillow. I could see that `pillow-simd` gains much more over stock pillow and would love to recommend `pillow-simd` for `imgp`.

I have run my tests with 2000 images and found no issues with `pillow-simd` as the backend to `imgp`. So thought of confirming with you as well.

`imgp` uses the `multiprocessing` module and converts one image per core with a global lock in place to `print` informative messages to `stdout`. Do you see any issue with using `pillow-simd`?

**Comment by homm** [comment]
It depends :-)

We are using SIMD version in production in the constant environment when we exactly know CPU capabilities. In opposite, your product can be run on different hardware. I think it is relatively safe to assume that target CPU has SSE4 support nowadays, but not 100% safe.

**Comment by jarun** [comment]
Sorry, if I wasn't clear. Yes, I meant if the CPU supports SIMD.

**Comment by jarun** [comment]
Closing as query answered.
