### ISSUE TITLE
Question, possible answer, for problems building on Windows 10.

### ISSUE THREAD

**Issue by emerth** [uploadcare/pillow-simd#112]
### What did you do?

Tried to build on Window 10 using VS2019.

### What did you expect to happen?

Successful build.

### What actually happened?

Build failed in link stage. Missing various ZSTD and libdeflate functions.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.6.9
* Pillow: Head, Feb 8 2022.
* Compiler: Visual Studio 2019 Enterprise

The build instructions for Windows do not pull in libdeflate nor the ztsd library. They need to be installed and added to the setup.py script. 

I tried to send a pull request with a change to winbuild/README.md, but it landed at https://github.com/python-pillow/Pillow, not uploadcare. Seemed like a request to merge all of uploadcare/pillow-simd, which they very reasonably declined to do. Very embarrassing.

Is this an update you are interested in? I can try to send a new pull req, or just post the changes here... they are pretty small.

**Comment by hugovk** [comment]
When making a PR, by default it goes to the upstream.

But you can choose to make it against another fork instead.

At the "Open a pull request" page, click on the "base repository: python-pillow/Pillow" button:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/1324225/153703578-bf6e84ff-c228-4094-b46d-85f99b8eceb0.png">

Then start typing "uploadcare" into the filter and select this fork:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/1324225/153703549-61def43e-4bcd-4eb3-a82c-136b2cd7c0dc.png">

And in the preview you should hopefully only see your new commits.

**Comment by emerth** [comment]
I see. Thank you! I will send along a pull request this weekend.

**Comment by homm** [comment]
> The build instructions for Windows do not pull in libdeflate nor the ztsd library. They need to be installed and added to the setup.py script.

I believe this is not related to Pillow-SIMD. Please send this changes to the upstream https://github.com/python-pillow/Pillow
