### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by rphlo** [uploadcare/pillow-simd#124]
I noticed the tag for 9.2.0 is out there but the PyPI version is still stuck at 9.0.0.post1

Can we expect a new PyPI release?

Thanks for the development effort.

**Comment by chrisapplegate** [comment]
This would very much appreciated here as well, thanks in advance

**Comment by matthiasBT** [comment]
Hi! Could we please get a 9.2.0 PyPI release? Thanks!

**Comment by yelinaung** [comment]
I've worked around this by doing this in my `requirements.txt`

```
git+https://github.com/uploadcare/pillow-simd@9.2.0
```

**Comment by homm** [comment]
@yelinaung there is no reasons to do this. You just installing regular Pillow (without SIMD optimizations)

**Comment by yelinaung** [comment]
> @yelinaung there is no reasons to do this. You just installing regular Pillow (without SIMD optimizations)

Sorry I am not getting what you mean. What is the suggested way to install the latest commit or tag of the Pillow-SIMD?

**Comment by homm** [comment]
This repo is a fork of original Pillow, so you can find original tags and branches from the original Pillow here. `9.2.0` is a tag from the original source tree. The latest Pillow-SIMD version is `v9.0.0.post1` for now.

**Comment by MvGulik** [comment]
Now I'm even more confused than before.

O well. Such is life I guess.
