### ISSUE TITLE
Compare speed with Simd library

### ISSUE THREAD

**Issue by tonal** [uploadcare/pillow-simd#13]
Please add [Simd image processing library](https://github.com/ermig1979/Simd) to your benchmarks

**Comment by homm** [comment]
Hi!

First of all, benchmarks in the README is outdated a bit. There are [separate project](https://github.com/python-pillow/pillow-perf) and [page](https://python-pillow.org/pillow-perf/) with much more detailed benchmarks of many operations and libraries.

As of SIMD library, there are a number of operations which are interesting for benchmarks. You can find the list in the [result section](https://python-pillow.org/pillow-perf/#results):
Resize, Blur, Transposition, Color conversion, Alpha composition.

I don't see generic convolution resampling in the "Simd Library", only a very limited set of special cases, plus bilinear resampling without convolutions. I also can't find blur, transposition or alpha composition operations in this library. I only see RGB to L color conversion. So I don't see any reasons to add just one operation to benchmarks.

Please point me out in [pillow-perf issues](https://github.com/python-pillow/pillow-perf/issues) if I'm wrong.
