### ISSUE TITLE
PIP install process and one suggestion.

### ISSUE THREAD

**Issue by BobSquarePants** [uploadcare/pillow-simd#130]
Hi @homm ,

From what I can read in the install section of pillow-simd. It look like the pip install willl trigger a compilation, correct ?

Therefore we need to install the [prerequisites](https://pillow.readthedocs.io/en/stable/installation.html#building-from-source).

On my system I have already `libjpeg62-turbo` installed is that enough / can replace `libjpeg`

**Suggestion**
in github you can open a discussions section, it's really nice for question like this , that are not per se issues. and if it happen that it is an issues it can be converted as such.
So it's help dev. to focus and issues & questions...

Cheers,

**Comment by homm** [comment]
Please read the link you provided carefully. There are samples for different systems and link to dockerfiles.
