### ISSUE TITLE
Failed to install on Devuan.

### ISSUE THREAD

**Issue by BobSquarePants** [uploadcare/pillow-simd#131]
> What did you do?

```shell
apt install zlib1g-dev libjpeg-dev build-essential
```

`pip install pillow-simd` (inside a venv)

> What did you expect to happen?

Flawless install :)

> What actually happened?

Get an error ouput

    Collecting pillow-simd
    Using cached Pillow-SIMD-9.0.0.post1.tar.gz (849 kB)
    Using legacy 'setup.py install' for pillow-simd, since package 'wheel' is not installed.
    Installing collected packages: pillow-simd
        Running setup.py install for pillow-simd ... error
        ERROR: Command errored out with exit status 1:
        command: /AvenvPath/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h5a8el5a/install-record.txt --single-version-externally-managed --compile --install-headers /AvenvPath/include/site/python3.9/pillow-simd
            cwd: /tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5/
        Complete output (154 lines):
        running install
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-3.9
        creating build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/_version.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/features.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/Image.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/_util.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
        running egg_info
        writing src/Pillow_SIMD.egg-info/PKG-INFO
        writing dependency_links to src/Pillow_SIMD.egg-info/dependency_links.txt
        writing top-level names to src/Pillow_SIMD.egg-info/top_level.txt
        reading manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no files found matching '*.c'
        warning: no files found matching '*.h'
        warning: no files found matching '*.sh'
        warning: no directories found matching 'Tests'
        no previously-included directories found matching 'Tests'
        warning: no previously-included files found matching '.appveyor.yml'
        warning: no previously-included files found matching '.clang-format'
        warning: no previously-included files found matching '.coveragerc'
        warning: no previously-included files found matching '.editorconfig'
        warning: no previously-included files found matching '.readthedocs.yml'
        warning: no previously-included files found matching 'codecov.yml'
        warning: no previously-included files matching '.git*' found anywhere in distribution
        warning: no previously-included files matching '*.pyc' found anywhere in distribution
        warning: no previously-included files matching '*.so' found anywhere in distribution
        no previously-included directories found matching '.ci'
        writing manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
        running build_ext
        building 'PIL._imaging' extension
        building 'PIL._imagingmath' extension
        building 'PIL._imagingtk' extension
        creating build/temp.linux-x86_64-3.9
        creating build/temp.linux-x86_64-3.9/src
        creating build/temp.linux-x86_64-3.9/src
        creating build/temp.linux-x86_64-3.9/src
        building 'PIL._imagingmorph' extension
        creating build/temp.linux-x86_64-3.9/src/Tk
        x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5 -I/AvenvPath/include -I/usr/local/include -I/usr/include -I/AvenvPath/include -I/usr/include/python3.9 -c src/_imagingmorph.c -o build/temp.linux-x86_64-3.9/src/_imagingmorph.o
        creating build/temp.linux-x86_64-3.9/src/libImaging
        x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5 -I/AvenvPath/include -I/usr/local/include -I/usr/include -I/AvenvPath/include -I/usr/include/python3.9 -c src/_imagingmath.c -o build/temp.linux-x86_64-3.9/src/_imagingmath.o
        x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5 -I/AvenvPath/include -I/usr/local/include -I/usr/include -I/AvenvPath/include -I/usr/include/python3.9 -c src/Tk/tkImaging.c -o build/temp.linux-x86_64-3.9/src/Tk/tkImaging.o
        x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -DPILLOW_VERSION="9.0.0.post1" -I/tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5 -I/AvenvPath/include -I/usr/local/include -I/usr/include -I/AvenvPath/include -I/usr/include/python3.9 -c src/_imaging.c -o build/temp.linux-x86_64-3.9/src/_imaging.o -msse4
        src/_imagingmorph.c:14:10: fatal error: Python.h: No such file or directory
        14 | #include "Python.h"
            |          ^~~~~~~~~~
        src/_imaging.c:75:10: fatal error: Python.h: No such file or directory
        75 | #include "Python.h"
            |          ^~~~~~~~~~
        src/_imagingmath.c:16:10: fatal error: Python.h: No such file or directory
        16 | #include "Python.h"
            |          ^~~~~~~~~~
        compilation terminated.
        compilation terminated.
        compilation terminated.
        In file included from src/Tk/../libImaging/Imaging.h:13,
                        from src/Tk/tkImaging.c:42:
        src/Tk/../libImaging/ImPlatform.h:10:10: fatal error: Python.h: No such file or directory
        10 | #include "Python.h"
            |          ^~~~~~~~~~
        compilation terminated.
        error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
        ----------------------------------------
    ERROR: Command errored out with exit status 1: /AvenvPath/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ycy1rm8e/pillow-simd_2ccbe42c4a3845078a66bb0cafa7d1b5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h5a8el5a/install-record.txt --single-version-externally-managed --compile --install-headers /AvenvPath/include/site/python3.9/pillow-simd Check the logs for full command output.

### What are your OS, Python and Pillow versions?

* OS: [Devuan](https://www.devuan.org)
* Python: 3.9
* Pillow: Not installed.

**Comment by homm** [comment]
> #include "Python.h"

You need `python-dev` package
