### ISSUE TITLE
issue with heic files using Pillow-SIMD but not Pillow

### ISSUE THREAD

**Issue by jzstoller** [uploadcare/pillow-simd#133]
### What did you do?

Compare conversion of an heic file to jpg using either Pillow or Pillow-SIMD

### What did you expect to happen?

Conversion will execute with Pillow and Pillow-SIMD

### What actually happened?

This error message occured with Pillow-SIMD but executes perfectly with Pillow:
PIL.UnidentifiedImageError: cannot identify image file "/Users/testuser/testimage.heic"

### What are your OS, Python and Pillow versions?

* OS: MacOs 13.6.1
* Python: 3.11.5
* Pillow: pillow-10.1.0 or Pillow-SIMD-9.0.0.post1

```python
from PIL import Image
from pillow_heif import register_heif_opener

register_heif_opener()

im = Image.open('testimage.heic')
im.thumbnail((200, 200))
im.save('test.jpg', 'jpeg')

```

**Comment by jzstoller** [comment]
Hi,

Would you mind commenting if there is an answer to this issue? Was my description not detailed enough?

thank you

**Comment by homm** [comment]
https://github.com/uploadcare/pillow-simd#contributing-to-pillow-simd

**Comment by jzstoller** [comment]
Thank you for the quick reply. I believe this is an SIMD bug...not a general Pillow bug. The script works fine when  pillow-10.1.0 is installed but does not work when Pillow-SIMD-9.0.0.post1 is installed.

**Comment by jzstoller** [comment]
For those who have this same issue. The Pillow-SIMD version (9.0.0.post1) on pypi.org is not up to date and therefore does not work with pillow_heif. Pillow version >=9.1.1 is required for pillow_heif (since 0.13.0).

see [here](https://github.com/bigcat88/pillow_heif/issues/176)
From pillow_heif changelog:
[0.13.0 - 2023-08-09]
- Minimum required `Pillow` version increased from `8.4.0` to `9.1.1`

**To solve the problem**, download pillow_simd 9.5.0 from github and install:

`pip install '/Users/username/Downloads/pillow-simd-9.5.0.zip'`
