### ISSUE TITLE
Premultiplied alpha and integration with cairo ?

### ISSUE THREAD

**Issue by stuaxo** [uploadcare/pillow-simd#2]
Does this use premultiplied alpha ?

I assume it might do, as this would make things efficient for SIMD.

I ask, as it is the native pixel format (BaGaRaA) for cairo, so it could make integration with that library efficient + straightforward.

**Comment by homm** [comment]
Originally Pillow works with [many modes](http://pillow.readthedocs.io/en/3.2.x/handbook/concepts.html#modes), one of them is `RGBa` (true color with premultiplied alpha). Internally, Pillow [converts `RGBA` images to `RGBa` before resizing and convert back after](https://github.com/python-pillow/Pillow/blob/3.2.x/PIL/Image.py#L1547-L1548).

Pillow-SIMD doesn't change any behavior of original Pillow.
