### ISSUE TITLE
not support webp?

### ISSUE THREAD

**Issue by Maslino** [uploadcare/pillow-simd#20]
### What did you do?
installed the latest version of pillow-simd and then test it against a webp image.

### What did you expect to happen?
pillow-simd should identify webp image.

libwebp has already been installed.
```
[root@01065038-83ac-4563-a33b-5542de40a0de static]# ldconfig -p|grep -i webp
        libwebpmux.so.0 (libc6,x86-64) => /lib64/libwebpmux.so.0
        libwebp.so.4 (libc6,x86-64) => /lib64/libwebp.so.4
```

### What actually happened?
IOError when opening a webp image:
```
[root@01065038-83ac-4563-a33b-5542de40a0de static]# ll
total 1680
-rw-r--r-- 1 root root  176972 Dec 14 18:29 cherry.webp
-rw-r--r-- 1 root root  163759 Dec 14 18:29 dog.jpg
-rw-r--r-- 1 root root   42927 Dec 14 18:29 face.jpg
-rw-r--r-- 1 root root  107954 Dec 14 18:29 jobs.png
-rw-r--r-- 1 root root 1216868 Dec 14 18:29 test.gif
[root@01065038-83ac-4563-a33b-5542de40a0de static]# python
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.open('cherry.webp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2519, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'cherry.webp'
```

### What versions of Pillow and Python are you using?
I have tried the latest version(4.3.0.post0) and 4.2.1.post0 of pillow-simd

Python version: 2.7.5

Github doesn't support webp image upload. The test image is here: http://www.gstatic.com/webp/gallery/4.webp

**Comment by homm** [comment]
> libwebp has already been installed

How exactly was it installed? If from OS repos, you'll need dev packages too. See [build from sources](http://pillow.readthedocs.io/en/4.3.x/installation.html#building-from-source) section.

**Comment by Maslino** [comment]
@homm yes, it's from OS repos. libwebp-devel wasn't installed. I will check that.

**Comment by Maslino** [comment]
after installed libwebp-devel, all is ok! thanks @homm
