### ISSUE TITLE
What proofs are run to verify output is consistent?

### ISSUE THREAD

**Issue by funkybob** [uploadcare/pillow-simd#21]
Are there any test suites or existing efforts to show the output of Pillow-SIMD is at least close to what Pillow would produce?

Some searching has not turned out anything apparent.

**Comment by homm** [comment]
Pillow and Pillow-SIMD produce the same output for all operations excluding resampling. For resampling, there could be ±1 difference in result values on each pixel due to lower precision of intermittent coefficients. The proofs are Pillow's tests which are the same for Pillow-SIMD.
