### ISSUE TITLE
TIFF input is broken (OSError: image file is truncated)

### ISSUE THREAD

**Issue by sp-1234** [uploadcare/pillow-simd#22]
### What did you do?
	import PIL.Image as Image

	with open('image.tiff', 'rb') as f:
	    i = Image.open(f)
	    i.load()

### What did you expect to happen?
Image is loaded normally

### What actually happened?
	Traceback (most recent call last):
	  File "example.py", line 5, in <module>
	    i.load()
	  File "/usr/local/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 1053, in load
	    return super(TiffImageFile, self).load()
	  File "/usr/local/lib/python3.6/site-packages/PIL/ImageFile.py", line 233, in load
	    "(%d bytes not processed)" % len(b))
	OSError: image file is truncated (763 bytes not processed)

### What versions of Pillow and Python are you using?
	$ python3 --version
	Python 3.6.3

	$ pip3 freeze | grep -i pil
	Pillow-SIMD==4.3.0.post0

### The affected image file (gzipped):
[image.tiff.gz](https://github.com/uploadcare/pillow-simd/files/1579332/image.tiff.gz)
The image is accepted just fine by ImageMagick and pretty much everything else

**Comment by homm** [comment]
Did you get the same error with Pillow (without SIMD)? If yes, please fill the issue [there](https://github.com/python-pillow/Pillow/issues/new).

**Comment by homm** [comment]
For truncated files, you could try to set `LOAD_TRUNCATED_IMAGES` constant:

```python
from PIL import Image, ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.open('image.tiff').save('_out.jpeg')
```


Please, next time direct Issues not related to SIMD to Pillow main repo.
