### ISSUE TITLE
Do you have any CPU resources usage comparison with original Pillow?

### ISSUE THREAD

**Issue by alexandertsema** [uploadcare/pillow-simd#23]

**Comment by homm** [comment]
What do you mean by "CPU resources"? As any CPU-bound operation, image manipulations use 100% CPU until they are done.

**Comment by alexandertsema** [comment]
@homm Thanks for the reply, Alex. I mean CPU time, but ok sounds legit. Do you have benchmarks with openCV vs Pillow-SIMD? Looks like openCV uses SIMD by default (and even can be compiled with gpu enabled). BTW I'm building a new image resizing service for production, currently, we use https://imageresizing.net/ which is pretty fast and does not load CPU to 100%, usually around 89% for the same load as for the pillow one, but I believe it's because of some web server tweaking.
Is jpeg compression SIMD optimized? Are all the resizing methods SIMD optimized?

**Comment by homm** [comment]
> Do you have benchmarks with openCV vs Pillow-SIMD?

https://python-pillow.github.io/pillow-perf/

> Is jpeg compression SIMD optimized?

This depends on your JPEG codec installed in the system and compiled with Pillow. Many Linux distros use libjpeg-turbo by default which is highly optimized.

> Are all the resizing methods SIMD optimized?

No, Nearest neighbor method and [affine transformations](https://pillow.readthedocs.io/en/5.0.0/reference/Image.html#PIL.Image.Image.transform) are not SIMD-optimized.
