### ISSUE TITLE
JPEG decoding is faster in benchmarks, but README does not mention it

### ISSUE THREAD

**Issue by lopuhin** [uploadcare/pillow-simd#27]
README currently mentions several operations that are SIMD accelerated, but JPEG decoding is not one of them (https://github.com/uploadcare/pillow-simd/blame/simd/4.3.x/README.md#L45-L52). But according to our benchmarks, JPEG decoding is about 2x faster than for Pillow. Is decoding really accelerated and it is just not reflected in README?

**Comment by homm** [comment]
JPEG decoding is done by libjpeg-turbo. The speed should be the same as in vanilla Pillow. I can imagine that for some reasons your Pillow precompiled installation uses system's libjpeg, while Pillow-SIMD uses libjpeg-turbo. You could try to force Pillow to rebuild from sources to verify that theory.

**Comment by homm** [comment]
By the way, you are right that the list is a bit outdated, there are several other functions which are accelerated in the latest version.

**Comment by lopuhin** [comment]
> JPEG decoding is done by libjpeg-turbo. The speed should be the same as in vanilla Pillow.

That's interesting, I thought I was comparing against pre-compiled libjpeg-turbo, maybe the difference lies here, will double-check. Thanks for the pointer!

**Comment by homm** [comment]
Readme updated
