### ISSUE TITLE
Animated WebP not supported

### ISSUE THREAD

**Issue by kgriffs** [uploadcare/pillow-simd#29]
It looks like pillow-simd doesn't support animated WebP since it's WebPImagePlugin.py is behind upstream's. It would be awesome to get this into pillow-simd.

**Comment by homm** [comment]
I'm planning update to 5.1 near future.

**Comment by kgriffs** [comment]
Looking forward to it, thanks!

**Comment by homm** [comment]
Pillow-SIMD 5.5.1.post0 is released.
