### ISSUE TITLE
Check out libsimdpp, it should help supporting multiple platforms

### ISSUE THREAD

**Issue by p12tic** [uploadcare/pillow-simd#3]
Hi, just noticed this new SIMDified library in development through a Hacker News post. If cross-platform SIMD support is among your objectives, I think you should check out libsimdpp (https://github.com/p12tic/libsimdpp). It allows you to write the SIMD code once, then compile it for different instruction sets, combine the resulting object files into single library and then dispatch depending on the actual CPU type on runtime. For relatively simple code such as image processing such multi-platform support would be straightforward. At the moment libsimdpp already supports the most popular SIMD instruction sets: SSE2 to SSE4.1, XOP, AVX, AVX2, AVX512F, NEON and Altivec, with AVX512BW/DQ, MIPS MSA and POWER7/8 VSX support being in development.

Disclosure: I'm the author of libsimdpp.

**Comment by funny-falcon** [comment]
Other possible approach https://gcc.gnu.org/wiki/FunctionMultiVersioning
(looks to be working with clang as well)

**Comment by p12tic** [comment]
Unfortunately this only solves dynamic dispatch problem and simplifies infrastructure for multiple instruction set support. The fact that one needs to use different SIMD instructions for each instruction set is not addressed.

**Comment by funny-falcon** [comment]
@p12tic you are right. But lets authors decide.

And Pillow is written in C.

**Comment by homm** [comment]
Sorry, I don't believe that is possible to rewrite some complicated parts on the higher level and keep original performance. For example, in the next release, [I'm going to](https://github.com/uploadcare/pillow-simd/blob/simd/resample-adaptive/libImaging/ResampleSIMDVerticalConv.c) heavily use `_mm_madd_epi16` intrinsic. I haven't found it in `libsimdpp`. But you always can change my mind by showing the way.

Also, as @funny-falcon said, Pillow and whole Python toolchain is written is C. I'm not sure if it possible to use C++ and also I don't familiar with it at all.
