### ISSUE TITLE
AVX2 version failed on non AVX2 CPU

### ISSUE THREAD

**Issue by alexandertsema** [uploadcare/pillow-simd#30]
### What did you do?
Run
`CC="cc -mavx2" pip install -U --force-reinstall pillow-simd`
on avx CPU, not avx2

### What did you expect to happen?
to be installed ignoring this flag or gracefully failover

### What actually happened?
it was installed but any call of the library crashes with `142 Illegal instruction (core dumped) python3`

### What versions of Pillow and Python are you using?
4.3post, Python 3.6.3, Alpine docker

**Comment by homm** [comment]
This is expected behavior. If you aren't sure that all target CPUs have avx2 support, you shouldn't use -mavx2 flag.

> to be installed ignoring this flag or gracefully failover

If it works that way, no flag needed at all )

**Comment by alexandertsema** [comment]
I there any way to compile it for AMD Opteron(tm) Processor 4171 HE? 
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow rep_good nopl extd
_apicid pni cx16 popcnt hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw vmmcall @homm

**Comment by homm** [comment]
@alexandertsema I'm afraid, no. As I see, that CPU fairly old and doesn't have the required SSE4.1 and SSE4.2 instruction sets.

**Comment by alexandertsema** [comment]
makes sense, thanks for reply!
