### ISSUE TITLE
Maybe should add additional functionality saving aspect ratio for resizing method.

### ISSUE THREAD

**Issue by ghost** [uploadcare/pillow-simd#39]
Should add additional functionality saving aspect ratio for resizing method.

Something like this
`

    def resize(self, size, resample=NEAREST, box=None, save_ratio=False):
        if save_ratio:
            ratio_width = float(size[0] / float(self.im.width))
            ratio_height = float(size[1] / float(self.im.height))

            ratio = min(ratio_height, ratio_width)

            width = int(float(self.im.width) * ratio)
            height = int(float(self.im.height) * ratio)

            size = (width, height)   
`

**Comment by hugovk** [comment]
Like `thumbnail`?

https://pillow.readthedocs.io/en/5.2.x/reference/Image.html#create-thumbnails

```python
    def thumbnail(self, size, resample=BICUBIC):
        """
        Make this image into a thumbnail.  This method modifies the
        image to contain a thumbnail version of itself, no larger than
        the given size.  This method calculates an appropriate thumbnail
        size to preserve the aspect of the image, calls the
        :py:meth:`~PIL.Image.Image.draft` method to configure the file reader
        (where applicable), and finally resizes the image.
        Note that this function modifies the :py:class:`~PIL.Image.Image`
        object in place.  If you need to use the full resolution image as well,
        apply this method to a :py:meth:`~PIL.Image.Image.copy` of the original
        image.
        :param size: Requested size.
        :param resample: Optional resampling filter.  This can be one
           of :py:attr:`PIL.Image.NEAREST`, :py:attr:`PIL.Image.BILINEAR`,
           :py:attr:`PIL.Image.BICUBIC`, or :py:attr:`PIL.Image.LANCZOS`.
           If omitted, it defaults to :py:attr:`PIL.Image.BICUBIC`.
           (was :py:attr:`PIL.Image.NEAREST` prior to version 2.5.0)
        :returns: None
        """

        # preserve aspect ratio
        x, y = self.size
        if x > size[0]:
            y = int(max(y * size[0] / x, 1))
            x = int(size[0])
        if y > size[1]:
            x = int(max(x * size[1] / y, 1))
            y = int(size[1])
        size = x, y

        if size == self.size:
            return

        self.draft(None, size)

        im = self.resize(size, resample)

        self.im = im.im
        self.mode = im.mode
        self.size = size

        self.readonly = 0
        self.pyaccess = None
```

https://github.com/uploadcare/pillow-simd/blob/simd/5.1.x/src/PIL/Image.py#L2035-L2080

**Comment by ghost** [comment]
@hugovk It only works if the original image size is more than the size that you want to get.
For example, the original image has size like (10, 8), but you want to get (640, 480). thumbnail method does not save aspect ratio. Because it is intended  only for creating thumbnail

**Comment by homm** [comment]
save_ratio=True/False is not enough for all cases. What if you want an image not less than given size? What if you only have desired width or height? All of this is out of the scope of the base Image.resize() method. It's better to add helper in `ImageOps` for this.

And again, this is not related to Pillow-SIMD )
