### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by ghost** [uploadcare/pillow-simd#40]
### TypeError: object of type 'NoneType' has no len()

This image has a value "comment" is None. It raises that error.  

[https://github.com/uploadcare/pillow-simd/blob/simd/5.1.x/src/PIL/GifImagePlugin.py#L527](url)
```
    if "comment" in im.encoderinfo and 1 <= len(im.encoderinfo["comment"]) <= 255:
        fp.write(b"!" +
                 o8(254) +                # extension intro
                 o8(len(im.encoderinfo["comment"])) +
                 im.encoderinfo["comment"] +
                 o8(0))
```
[https://github.com/uploadcare/pillow-simd/blob/simd/5.1.x/src/PIL/GifImagePlugin.py#L694](url)
```
    for extensionKey in ["transparency", "duration", "loop", "comment"]:
        if info and extensionKey in info:
            if ((extensionKey == "duration" and info[extensionKey] == 0) or
               (extensionKey == "comment" and info[extensionKey] is not None and not (1 <= len(info[extensionKey]) <= 255))):
                continue
            version = b"89a"
            break
```

```
{'background': 160,
 'comment': None,
 'duration': 500,
 'optimize': True,
 'version': b'GIF89a'}
```

![image](https://user-images.githubusercontent.com/9821654/44532276-6bc6e880-a6fb-11e8-8f18-d717439b8f9f.png)

**Comment by hugovk** [comment]
This and your other issue and pull request really belong to the upstream Pillow project. 

Please see:

https://github.com/uploadcare/pillow-simd/blob/simd/5.1.x/README.md#contributing-to-pillow-simd
