### ISSUE TITLE
`img.convert(RGB)` cuases OSError

### ISSUE THREAD

**Issue by moskomule** [uploadcare/pillow-simd#42]
### What did you do?

I tried to convert images in https://tiny-imagenet.herokuapp.com/ to RGB as the following code. 

```
base = pathlib.Path("tinyimagenet/train")
for d in base.iterdir():
    for i in d.glob("*.JPEG"):
         with open(i, 'rb') as f:
             try:
                 Image.open(f).convert("RGB")
             except OSError:
                 print(f"error: {i}")
```

### What did you expect to happen?

The same code causes no error on pure Pillow and I didn't expect any trouble.

### What actually happened?

Not all but many images caused `OSError broken data stream when reading image file`.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu
* Python:  Python 3.6
* Pillow: I followed the instruction https://gist.github.com/soumith/01da3874bf014d8a8c53406c2b95d56b to install pillow.

**Comment by homm** [comment]
> The same code causes no error on pure Pillow and I didn't expect any trouble

Are you sure than versions match? Which versions did you try?

**Comment by moskomule** [comment]
Sure. Both are v5.3.0.

**Comment by homm** [comment]
Could you provide a test image?

**Comment by homm** [comment]
> Sure. Both are v5.3.0.

Wait a moment, Pillow-SIMD 5.3.0 was released today after you post a comment )

**Comment by moskomule** [comment]
I built SIMD from source (`5.3.0.post0`).

**Comment by moskomule** [comment]
Some examples cause OSError.

![n07583066_154](https://user-images.githubusercontent.com/11806234/47199605-572a6800-d3ad-11e8-922f-38d6d60c4a32.JPEG)
![n07583066_319](https://user-images.githubusercontent.com/11806234/47199606-572a6800-d3ad-11e8-9dcf-e945f4753e7c.JPEG)
![n07583066_326](https://user-images.githubusercontent.com/11806234/47199607-572a6800-d3ad-11e8-81c8-46cacd184fbb.JPEG)

**Comment by homm** [comment]
I've tested Pillow & Pillow-SIMD from 5.0 to 5.3, all of them are successful. The problem is elsewhere. You could try this suggestion: 
https://gist.github.com/soumith/01da3874bf014d8a8c53406c2b95d56b#gistcomment-2657191

**Comment by netw0rkf10w** [comment]
I've encountered the same issue. Do you remember how you resolved this please, @moskomule? Thanks.

**Comment by moskomule** [comment]
If I remember correctly, I just gave up using Pillow-SIMD and used Pillow instead.

**Comment by netw0rkf10w** [comment]
> If I remember correctly, I just gave up using Pillow-SIMD and used Pillow instead.

Lol that is indeed a perfectly working solution haha :))

**Comment by netw0rkf10w** [comment]
It seems that this issue is related to `libjpeg-turbo` (which I had installed previously before installing Pillow-SIMD).

I found a solution [here](https://github.com/python-pillow/Pillow/issues/3185#issuecomment-400247704):

```python
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

path = "/home/data/imagenet/val/n03146219/ILSVRC2012_val_00027260.JPEG"
with open(path, "rb") as f:
        img = Image.open(f)
        im = img.convert("RGB")
```

The error no longer occurs. However, another comment in that thread stated that the above only loads first rows of the image. To see how the image was loaded, I tried saving it for visualization:

```python
im.save("/home/Downloads/ILSVRC2012_val_00027260_RGB.jpg")
```

but then I obtained the following errors:

```
Wrong JPEG library version: library is 90, caller expects 62
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.10/site-packages/PIL/Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "/home/.local/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 783, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/home/.local/lib/python3.10/site-packages/PIL/ImageFile.py", line 529, in _save
    raise OSError(f"encoder error {s} when writing image file")
OSError: encoder error -2 when writing image file
```

I am not sure why this happens...

**Comment by netw0rkf10w** [comment]
I turns out that my Conda environment already has its own `libjpeg`, which caused the issue:

```
(python-3.10.4) ldd build/lib.linux-x86_64-cpython-310/PIL/_imaging.cpython-310-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffe31bd4000)
	libjpeg.so.9 => /home/anaconda-py3/envs/python-3.10.4/lib/libjpeg.so.9 (0x00007fc40f8ca000)
```

@homm Do you know if there is a way of forcing `python setup.py install` to prioritize libraries that I have in `~/.local/` over those inside the Conda environment? Thank you in advance for your response.
