### ISSUE TITLE
On using .postX to distinguish Pillow-SIMD from Pillow at run-time

### ISSUE THREAD

**Issue by stas00** [uploadcare/pillow-simd#45]
In README you say: 

> "Pillow-SIMD is "following" Pillow. Pillow-SIMD versions are 100% compatible drop-in replacements for Pillow of the same version. For example, Pillow-SIMD 3.2.0.post3 is a drop-in replacement for Pillow 3.2.0, and Pillow-SIMD 3.3.3.post0 — for Pillow 3.3.3."

I see plenty of .postX releases for Pillow: https://github.com/python-pillow/Pillow/releases, so I'm not sure how that strategy is working out in practice.

Perhaps there should be a more reliable way to tell Pillow-SIMD is used when PIL is loaded? Some kind of special symbol that's only defined in Pillow-SIMD?

**Comment by homm** [comment]
> I see plenty of .postX releases for Pillow

Thanks for noticing. I was not careful and pushed simd tags in the main repo. Now it's fixed.

> Perhaps there should be a more reliable way to tell Pillow-SIMD is used when PIL is loaded?

I'll think about it.
