### ISSUE TITLE
__m128i pointer needs to be aligned, but this is unaligned.

### ISSUE THREAD

**Issue by martincmartin** [uploadcare/pillow-simd#48]
https://github.com/uploadcare/pillow-simd/blob/17582f734c2e95fe2b156faa361809961257b94f/src/libImaging/ResampleSIMDHorizontalConv.c#L356

Can use _mm_cvtsi32_si128() or _mm_loadu_si32() instead.

This should trigger whenever the kernel width is odd, I'm surprised it hasn't triggered for you?

**Comment by martincmartin** [comment]
It's also reading 128 bits then throwing away all but 32; those extra bits are beyond the end of the image, and could even be in the next page, which might not actually exist, and thus trying to read it might cause a seg fault or bus error.

**Comment by homm** [comment]
[`_mm_cvtepu8_epi32`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_cvtepu8_epi32&expand=1609) issues [`pmovzxbd`](https://www.felixcloutier.com/x86/pmovzx) instruction, which has two arguments:

```
PMOVZXBD xmm1, xmm2/m32
Zero extend 4 packed 8-bit integers in the low 4 bytes
of xmm2/m32 to 4 packed 32-bit integers in xmm1.
```

So, with memory argument it only reads 32 bits.

**Comment by martincmartin** [comment]
That's true in an optimized build, but in a non-optimized / debug build, there's a [`vmovdqa`](https://godbolt.org/z/hhPRbe) instruction before that.  I got a seg fault there in the debug build of my code.

So, this is undefined behavior according to the spec, and you're relying on the compiler to optimize it a certain way to produce correctness.

No worries if that's how you roll -- I've done that many times in the past myself.  :) Just thought you'd like to know.

**Comment by martincmartin** [comment]
The link above is to godbolt:  https://godbolt.org/z/hhPRbe

**Comment by homm** [comment]
This optimization gives measurable performance increase compared to `_mm_cvtepu8_epi32(_mm_cvtsi32_si128())` version. Do you have any ideas on how to save this optimization and avoid segfaults?

**Comment by martincmartin** [comment]
I think `_mm_loadu_si32()` does what you want:  https://gcc.godbolt.org/z/PoR8jk

The down side is, it doesn't seem to come in any of the intrinsics headers.  But the definition, which I copied from here: https://clang.llvm.org/doxygen/emmintrin_8h_source.html

seems to work well.  I don't know how portable it is though.

**Comment by homm** [comment]
`_mm_loadu_si32` generate additional `vmovd (%rdi), %xmm0` in all GCC versions exclude trunk.

**Comment by homm** [comment]
@martincmartin I'm implementing a fix, do you want to try it? 

Also, could you tell exactly compiler and options to reproduce the issue on debug builds with optimization? I can only catch this on non-optimized builds.

**Comment by homm** [comment]
> This optimization gives measurable performance increase

After careful testing the fix which forces a memory argument and the fix with `_mm_cvtsi32_si128` I came to the conclusion that performance is not suffering from extra instruction. So I'll fix this in near future and release all versions from `6.0.0.post1` to `7.0.0.post0`.

**Comment by mratsim** [comment]
In my own high performance code I always pass-by value SIMD instructions.
This seems be the same for this game dev: https://blog.molecular-matters.com/2011/10/18/simdifying-multi-platform-math/ but contrary to https://johanmabille.github.io/blog/2014/11/20/performance-considerations-about-simd-wrappers/ so I'm not really sure.

In any case for that loop the data should be hot in cache because it was touched in the loop before (unless it's a big loop? I don't know the range of xmax) and it's a easily predictable linear access so the `mov` cost should be unnoticeable (it's only instruction cache and decoding but no waiting on cache line).

**Comment by homm** [comment]
Pillow-SIMD 6.0.0.post1 with a fix is released. Please, try it.
https://pypi.org/project/Pillow-SIMD/#history
