### ISSUE TITLE
Does pillow-simd suport WEBP conversion?

### ISSUE THREAD

**Issue by vncsms** [uploadcare/pillow-simd#50]
### What did you do?

I tried convert a jpg image into WEBP image.

### What did you expect to happen?

I expect a conversion, without errors.

### What actually happened?

I got a error. When a install the the pillow: `pip install Pillow` the code works fine. But when: 

    $ pip uninstall pillow
    $ CC="cc -mavx2" pip install -U --force-reinstall pillow-simd

It's giving the error. 

Does pillow-simd suport WEBP conversion?

### What are your OS, Python and Pillow versions?

* OS: 

    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.5 LTS
    Release:        16.04
    Codename:       xenial

* Python: 

    Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
    Type "copyright", "credits" or "license" for more information.

    IPython 3.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

* Pillow: 

    Pillow-SIMD==5.3.0.post0

```python
    In [1]: import StringIO

    In [2]: from PIL import Image as PilImage

    In [3]: img = PilImage.open('222.jpg')

    In [4]: originalThumbStr = StringIO.StringIO()

    In [5]: img.convert('RGBA').save(originalThumbStr, 'webp', quality=75)
    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    <ipython-input-5-d3ca76f0559d> in <module>()
    ----> 1 img.convert('RGBA').save(originalThumbStr, 'webp', quality=75)

    /home/developer/.virtualenvs/prisvo/local/lib/python2.7/site-packages/PIL/Image.pyc in save(self, fp, format, **params)
       1956             save_handler = SAVE_ALL[format.upper()]
       1957         else:
    -> 1958             save_handler = SAVE[format.upper()]
       1959 
       1960         if open_fp:

    KeyError: 'WEBP'

    In [6]: 

```

**Comment by homm** [comment]
Pillow-SIMD supports the same things as regular Pillow, just follow [these steps](https://pillow.readthedocs.io/en/latest/installation.html#building-from-source) for installing optional dependencies.
