### ISSUE TITLE
AVX support for older CPUs

### ISSUE THREAD

**Issue by edwardCao** [uploadcare/pillow-simd#51]
Do we have plans to support older CPUs that have AVX but not AVX2? For example, Sandy Bridge era XEON CPUs circa 2011.

**Comment by homm** [comment]
No. This doesn’t make sense, since AVX1 provides only float operations (32-bit width), while most used operations in Pillow-SIMD are 16-bit integer operations, so SSE4 will be always faster than AVX1.

**Comment by homm** [comment]
To clarify: these CPU already supported through SSE4
