### ISSUE TITLE
Resize generate black band on image

### ISSUE THREAD

**Issue by Lucuz91** [uploadcare/pillow-simd#52]
### What did you do?
Just resize a image with a particular size

### What did you expect to happen?
Don't add black band on image

### What actually happened?
Add a black band on image

### What are your OS, Python and Pillow versions?

* OS: ubuntu 18.04
* Python: 2.7 and 3.7
* Pillow-simd: 5.3.0.post0

This code work well with pillow, but with pillow-simd the black band appear. 
Also if i change size works well, i don't understand why only with this image and this size.
I tried to replicate the thumbnail function without usate draft function, and works well, i don't know if this help to investigate.

```python
from PIL import Image
img = Image.open('original.jpg')
img.thumbnail((170,170), 1)
img.save('pillow-simd-converted.jpg')
```

Original image
![original](https://user-images.githubusercontent.com/18615313/55238538-0dd02580-5235-11e9-9f2d-767ec2564599.jpg)

Pillow-simd converted
![pillow-simd-converted](https://user-images.githubusercontent.com/18615313/55238587-2a6c5d80-5235-11e9-9640-343dc9666973.jpg)

**Comment by homm** [comment]
I can confirm the error. It appears during resizing with Lanczos filter when the width of the source image is 341 px and destination width is 170 px on Pillow-SIMD both complied with SSE4 and AVX2.
Minimal test case:

```python
im = Image.new('RGB', (341, 60), 'pink')
im.resize((170, 60), Image.LANCZOS).save('_out.png')
```

![_out](https://user-images.githubusercontent.com/128982/55400302-22266200-5556-11e9-940a-895f4cea1c99.png)

170 is related to 341 as `2x+1`, but the bug is not appear with other combinations of widths (for example, 321 and 160). Needs further investigation.

I'm sorry you're facing this weird thing.

**Comment by homm** [comment]
I found the bug, it was in the convolution coefficients normalisation to UINT16 type:

https://github.com/uploadcare/pillow-simd/commit/2eb555fdb8aa82bb5e9bd34434992cc934d23c6d#diff-704f59b07cceb3ff1645f2127d7e6d8cR298

The former implementation assumed a maximal coefficient value as a double on each step and compared it with int type range:
`maxkk < (1 << (MAX_COEFS_PRECISION-1)`

While in reality, the final value is calculated with rounding:
`(int) (0.5 + prekk[x] * (1 << coefs_precision))`

It so happened that given combination of parameters (341→170 resize with Lanczos filter) has lead to overflow (the maximum coefficient was outside the range of UINT16) in coefficients in two central pixels.

I've changed the condition and now it perfectly match following normalisation with rounding.

I'll tag the fix tomorrow. Thank you for finding this and sorry again.

**Comment by Lucuz91** [comment]
No, thanks to you, you have solved this strange problem very quickly. Thanks again for the support.

**Comment by homm** [comment]
I've released versions with fixes:
https://pypi.org/project/Pillow-SIMD/5.3.0.post1/
https://pypi.org/project/Pillow-SIMD/5.2.0.post1/
https://pypi.org/project/Pillow-SIMD/5.1.1.post1/

**Comment by homm** [comment]
I've done some research about the frequency of the overflow issue. I've tested all resize operations for the source size from 1 to 10'000 pixels and the destination size also from 1 to 10'000 using five available interpolation filters (500 million operations in the total). In theory, the overflow should happens in every 32'768th case, when limited factor is capacity of UINT16 type (more than 99% operations from given ranges). There are several conclusions:

* Overflow never happens for upscaling and downscaling in less than two times;
* There are 1906 overflows but the frequency is different for different interpolations:
  * Overflow never happens for BOX interpolation (rarely used);
  * For LINEAR interpolation overflow appears 103 times, i.e. every 970'873th operation;
  * HAMMING: 609 times, every 164'203th operation;
  * BICUBIC: 374 times, every 267'379th operation;
  * LANCZOS: 820 times, every 121'951th operation;
* With LINEAR and BICUBIC interpolations black bands appears only on the edges of an image.
* With LANCZOS interpolation black bands can appear at any part of an image. For example, here is a resizing from 2387x682px to 1190x340px using LANCZOS interpolation:

![1190x340-1](https://user-images.githubusercontent.com/128982/55522229-b72b7700-568c-11e9-8818-566bccc22359.jpeg)

The main reason why this error was undetected for so long time is that we are using a BICUBIC interpolation in production. By a Fluke, overflow for this interpolation has medium frequency and not very annoying appearance.

**Comment by homm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resize generate black band on image](https://trello.com/c/Kydr7tgR/432-resize-generate-black-band-on-image)

**Comment by Lucuz91** [comment]
Congratulations on the investigation, very accurate. 
We were lucky / unlucky to find this bug, since the probability of having it is really low.

But thanks to you now everything is solved, thanks again :)
