### ISSUE TITLE
Segfault in .thumbnail()

### ISSUE THREAD

**Issue by iclukas** [uploadcare/pillow-simd#53]
### What did you do?
Image.thumbnail()

### What did you expect to happen?
Resize the image

### What actually happened?
Segfault

### What are your OS, Python and Pillow versions?
* CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
* OS: Linux 4.14.78-gentoo #&#x2060;1 SMP  x86_64 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz GenuineIntel GNU/Linux
* Python: 3.6.5
* Pillow: 5.3.0.post1

Works with standard Pillow or on other CPUs, e.g. E5506.

```python
#!/usr/bin/python3
# -*- coding: UTF-8 -*-#

import os, argparse
from PIL import Image


def make_thumb(base_dir, full_file_name, width):

    file_name, file_extension = os.path.splitext(full_file_name)
    size = width, width

    if os.path.exists(base_dir + full_file_name):
        nImage = Image.open(base_dir + full_file_name)
        nImage.thumbnail(size, Image.ANTIALIAS)

        nFileName = str(base_dir) + str(file_name) + "_" + str(width) + str(file_extension)
        nImage.save(nFileName)

    else:
        print("file does not exists")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='generate a thumbnail from given picture, if it exists')
    parser.add_argument('-f', action="store", dest="file", type=str, required=True, help="")
    parser.add_argument('-w', action="store", dest="width", type=int, required=True, help="")
    parser.add_argument('-b', action="store", dest="base_dir", type=str, default="/www/test", required=False)
    args = parser.parse_args()
    make_thumb(args.base_dir, args.file, args.width)
```

**Comment by homm** [comment]
Which version GCC do you use? Is E5506 machine also has the same version?

**Comment by homm** [comment]
The most ovbious thing: the E5-2620 CPU doesn’t have AVX2 instrustions support. Are you sure you are compilled Pillow-SIMD without AVX2?

**Comment by iclukas** [comment]
gcc is at 8.2.0 on the E5506 machine and 6.3.0 on the other. But: I copied the working SSE4 build (only the binaries) from the smaller machine to the E5506 machine and still get a Segfault. 
nasm is at 2.14.02 (E5506) and 2.12.01.

Interestingly, it works fine when I call Pillow-SIMD via [imgp](https://github.com/jarun/imgp/blob/master/imgp) and process a whole directory. Even with AVX2 support.

**Comment by iclukas** [comment]
A few more tests show that sometimes thumbnail() works on a single file, depending on input and output size.

input | output | result
------|-------|------
4608x3456 | 7x5 | Segfault
4608x3456 | 8x6 | works
4608x3456 | 23x17 | Segfault
4608x3456 | 24x18 | works
4608x3456 | 512x384 | Segfault
4608x3456 | 1024x768 | Segfault
4608x3456 | 2304x1728 | works
1024x1024 | 7x5 | Segfault
1024x1024 | 8x6 | works
1024x1024 | 16x12 | works
1024x1024 | 24x18 | Segfault
1024x1024 | 512x384 | works
46x35 | 8x6 | Segfault
46x35 | 23x17 | Segfault

**Comment by homm** [comment]
> the E5-2620 CPU doesn’t have AVX2 instrustions support

Oh, I didn't noticed v4. This is Broadwell CPU with AVX2 support.

> But: I copied the working SSE4 build (only the binaries) from the smaller machine to the E5506 machine and still get a Segfault.

Could you elaborate, you said before: "Works on other CPUs, e.g. E5506". Do you mean you copied binary **from** E5506 (gcc 8.2.0) to E5-2620 v4?

**Comment by iclukas** [comment]
You are right, I mixed up the CPU names, sorry. Also, it didn’t really use the copied binaries, again sorry. There may be something wrong on the compiler side, I’ll do some better testing and keep you updated.

**Comment by iclukas** [comment]
Ok, I did some more tests. The funny thing is, it works with an AVX2 enabled build compiled on another machine with gcc 6.3.0. I set up another machine with gcc 8.2.0 and could successfully test on that machine. Alas the library paths differ, so I can’t test these binaries on the E5-2620 v4

I can’t put more time into this at the moment, so I’m closing the issue for now.

**Comment by chrhasse** [comment]
I am also experiencing this on two separate Arch Linux installs, one with an Intel i7-4790K, and one with an Intel i7-2640M. When built with GCC version 9.1.0, running the included test script ends in a segfault, however if I build with GCC version 8.3.0 it runs as expected. On the machine with a 4790k I also attempted to build it using GCC 9.1.0 and AVX2 enabled, but this did not make a difference.

```python
#!/usr/bin/python3
# -*- coding: UTF-8 -*-#

from PIL import Image
from io import BytesIO
import urllib.request

url="https://i.imgur.com/ZuOEFbO.jpg"
with urllib.request.urlopen(url) as resp:
    img = Image.open(BytesIO(resp.read()))
    img.thumbnail((250,250), Image.ANTIALIAS)
    img.save("/tmp/test.jpg")

```

I've also included the results of `coredumpctl info` [here](https://gist.github.com/chrhasse/c518c6f70d26c313b458fe40dfea843d), and can upload the coredump itself or any other info required if requested.

**Comment by homm** [comment]
@chrhasse it is possible that your case is duplicate of #48. I'll try to fix it for all compilers without performance regression.
