### ISSUE TITLE
Pillow SIMD 6.0.0 release?

### ISSUE THREAD

**Issue by okor** [uploadcare/pillow-simd#54]
Are there any plans/timelines for a 6.0.0 release?

Context: I am working on an issue regarding the `piexif` library that affects [thumbor](https://github.com/thumbor/thumbor/issues/1204). We can drop the `piexif` dependency with new [EXIF _write_ capabilities](https://pillow.readthedocs.io/en/stable/releasenotes/6.0.0.html#added-exif-class) in the Pillow 6.0.0 release. But there is a fairly strong desire to be able to use pillow-simd [[convo]](https://github.com/thumbor/remotecv/pull/23#discussion_r297881014). So it would really mean a lot to the Thumbor project if we could get a 6.0.0 release. 

Thanks for all your awesome work on pillow-simd!!

**Comment by homm** [comment]
Done 
https://pypi.org/project/Pillow-SIMD/#history

**Comment by okor** [comment]
@homm Wow. Thank you!!
