### ISSUE TITLE
L#139 identation typo in src/PIL/JpegImagePlugin.py  

### ISSUE THREAD

**Issue by igormq** [uploadcare/pillow-simd#55]
This was solved in Pillow PR [#3771](https://github.com/python-pillow/Pillow/pull/3771).

Fix: 
```bash
sed -i  '139s/.*/            self.info\[\"photoshop\"\] = photoshop/' src/PIL/JpegImagePlugin.py
```
[]'s,
Igor.

**Comment by homm** [comment]
Next versions of Pillow-SIMD is released.
https://pypi.org/project/Pillow-SIMD/#history
