### ISSUE TITLE
thumbnail just quits

### ISSUE THREAD

**Issue by ingoogni** [uploadcare/pillow-simd#57]
### What did you do?
```
C:\Users\ingo\Documents\Python\PostCamera\static\img\archive>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.__version__
'6.0.0.post0'
>>> from PIL import Image
>>> image = Image.open('a.jpg')
>>> image.thumbnail((100,100))

C:\Users\ingo\Documents\Python\PostCamera\static\img\archive>
```
EDIT: actually applying any form of filter to scale has the same result
```image.scale((100,100), Image.SomeFilterHere) ```

### What actually happened?
After using image.thumbnail python just quits.

### What are your OS, Python and Pillow versions?

* OS: win10 
* Python: 3.7
* Pillow: 6 (Gohlke compile)

**Comment by cgohlke** [comment]
Can't reproduce. Could you share `a.jpg` and CPU details?

**Comment by ingoogni** [comment]
CPU AMD Phenom II X6 1045ST, every image fails, jpg's are uploaded to a server from phones.
After your question I tested on a laptop Intel i7-3520M and there it works fine. (python 3.7.4 win10)

**Comment by cgohlke** [comment]
> CPU AMD Phenom II X6 1045ST

That CPU does not seem to have SSE4.1 and SSE4.2 instruction sets, just SSE4a.

**Comment by ingoogni** [comment]
Ah, just saw SSE4 and thought lets go, wasn't aware of the 'a' and that it makes a difference. Thanks. And thanks for all your compilations of python packages!
