### ISSUE TITLE
Benchmark details?

### ISSUE THREAD

**Issue by gi11es** [uploadcare/pillow-simd#6]
It would be nice to know at least the command or code used to produce the benchmark, in order to be able to run the same on our own hardware. Some ImageMagick and PIL methods are faster than others, so we don't really know what's being compared, as it stands.

**Comment by homm** [comment]
Sure. There is a link in [methodology](https://github.com/uploadcare/pillow-simd#methodology) section. 

Also, there is the [separate repository](https://github.com/homm/pillow-perf) with the advanced version of the script and more results from different Pillow versions including future releases.
