### ISSUE TITLE
Does PIllow need to be uninstalled before installing Pillow-SIMD?

### ISSUE THREAD

**Issue by tanagumo** [uploadcare/pillow-simd#81]
I need a library which depends on Pillow.
So installing this library overrides existing Pillow-SIMD codebase.

My current workaround is here.

```
pip install <library>
pip uninstall pillow
pip install pillow-simd
```

If I need not uninstall PIllow before installing Pillow-SIMD,  a requirements.txt is like below and I only have to do `pip install -r requirements.txt`.

```
pillow==7.0.0
<library>
pillow-simd==7.0.0.post3
```

**Comment by homm** [comment]
> Does PIllow need to be uninstalled before installing Pillow-SIMD?

Yes, otherwise no one can guarantee that exactly Pillow-SIMD is used.

You can use the following hack with `#egg=pillow`:

`requirements.txt`:
```
xhtml2pdf
git+git://github.com/uploadcare/pillow-simd.git@v7.0.0.post3#egg=pillow
```

```bash
$ python3.7 -m venv env_test

$ source ./env_test/bin/activate

$ pip install -U setuptools wheel pip
Successfully installed pip-20.0.2 setuptools-45.2.0 wheel-0.34.2

$ pip install -r requirements.txt
Successfully installed html5lib-1.0.1 pillow-simd-7.0.0.post3 pyPdf2-1.26.0 reportlab-3.5.34 six-1.14.0 webencodings-0.5.1 xhtml2pdf-0.2.4

$ pip freeze
html5lib==1.0.1
Pillow-SIMD==7.0.0.post3
pkg-resources==0.0.0
PyPDF2==1.26.0
reportlab==3.5.34
six==1.14.0
webencodings==0.5.1
xhtml2pdf==0.2.4
```

**Comment by tanagumo** [comment]
The problem was resolved with your advice.
Thanks.
