### ISSUE TITLE
How can I prevent packages installing Pillow?

### ISSUE THREAD

**Issue by realiti4** [uploadcare/pillow-simd#88]
Hi, even though I have pillow-simd installed, packages that requires Pillow install it as a dependency everytime I install a new package, or upgrading an existing one. Is there a trick to prevent this like installing pillow-simd as just pillow or something? Thanks

**Comment by homm** [comment]
We are using `#egg=pillow` postfix in `requirements.txt` like this:

```
-e git+https://github.com/uploadcare/pillow-simd.git@simd/6.0.x#egg=pillow
```
