### ISSUE TITLE
Box Blur number of passes is not controllable from Python

### ISSUE THREAD

**Issue by bmharper** [uploadcare/pillow-simd#89]
One of the great features of Pillow-SIMD is it's iterative box blur, but the number of passes cannot be controlled from Python.

Am I missing something here?

**Comment by homm** [comment]
There are no good reasons for complicating the  API. If you need only one pass (Box blur), there is separate filter for this. If you need Gaussian Blur, 3 passes is quite good approximation and doesn’t became better with more passes.

If you want something really strange, you can use low-level api and call `im.box_blur` and `im.gaussian_blur` with second argument, which number of passes.

**Comment by bmharper** [comment]
Thanks - so just to make sure - does this code end up inside `ImagingGaussianBlur` with `passes` = 3?
```python
im = im.filter(ImageFilter.GaussianBlur(radius))
```
I guess that's fine - 3 passes is OK.

**Comment by homm** [comment]
Right.
