### ISSUE TITLE
Installation: missing zlib library

### ISSUE THREAD

**Issue by oavrahami** [uploadcare/pillow-simd#90]
### What did you do?
Tried to install pillow-simd on a fresh environment:
```bash
$ pip install pillow-simd
```

### What did you expect to happen?
Installation goes successfully.

### What actually happened?
Got an error:
```
...
The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.
...
```

I've verified that I have the zlib library installed:
```
$ brew list | grep zlib
zlib
```

### What are your OS, Python and Pillow versions?

* OS: macOS 10.14.6
* Python: 7.7.8
* Pillow: No pillow is installed. I'm trying to install Pillow-SIMD-7.0.0.post3

**Comment by homm** [comment]
This is not SIMD-specific. Please follow this instruction: 
https://pillow.readthedocs.io/en/stable/installation.html#building-from-source

If you still have an issue with building Pillow from sources, [fill a report](https://github.com/python-pillow/Pillow/issues).
