### ISSUE TITLE
pip cant find the last tags: 7.1.2

### ISSUE THREAD

**Issue by casertap** [uploadcare/pillow-simd#91]
It seems that the current last tag: 7.1.2 is not available via pip install. 
Is it normal? this means that my current application is using 7.0.0.post3 and I am wondering if I am falling too much behind compared the original Pillow library.

Thanks

**Comment by SuperSandro2000** [comment]
Check https://pypi.org/project/Pillow-SIMD/#history for the latest released version which is 7.0.0.post3.

**Comment by homm** [comment]
https://pypi.org/project/Pillow-SIMD/7.1.2.post1/

**Comment by homm** [comment]
Versions `8.2.0.post0`, `8.3.2.post0` and `8.4.0.post0` released.
