### ISSUE TITLE
Pillow 8.x.x Support

### ISSUE THREAD

**Issue by hysrx** [uploadcare/pillow-simd#93]
Any considerations for Pillow 8.0.0/8.0.1/8.1.0 support?

Pillow Changelog: https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst

**Comment by jianlong-yuan** [comment]
any news?

**Comment by homm** [comment]
Versions `7.0.0.post4`, `7.1.2.post1`, `7.2.0.post1`, `8.0.1.post0` and `8.1.2.post0` released.

**Comment by homm** [comment]
Versions `8.2.0.post0`, `8.3.2.post0` and `8.4.0.post0` released.
