### ISSUE TITLE
Any timeline on updating pillow-simd?

### ISSUE THREAD

**Issue by w-** [uploadcare/pillow-simd#98]
pillow-simd is now a full major version behind official pillow.

are there any plans / timelines to update pillow-simd?

thanks

**Comment by MatrixScenary** [comment]
I'm surprised how this project is barely active. Ain't nobody's interested in massive speedups when using Pillow?

**Comment by w-** [comment]
i saw a tag 8.2.0
https://github.com/uploadcare/pillow-simd/tree/8.2.0

https://github.com/uploadcare/pillow-simd/releases/tag/8.2.0

is this a unofficial simd optimized version of 8.2 or just a copy of 8.2 from pillow ?
maybe @hugovk can comment?

**Comment by hugovk** [comment]
I'm not maintaining this project, but pillow-simd uses `.post` tags for releases, as detailed at https://github.com/uploadcare/pillow-simd#pillow-simd. The plain tags like `8.2.0` will be the "vanilla" Pillow tags.

**Comment by w-** [comment]
Thanks for replying.

**Comment by jianlong-yuan** [comment]
any news? Is the final conclusion that this version has been updated to 8.x.x?

**Comment by jhagege** [comment]
> any news? Is the final conclusion that this version has been updated to 8.x.x?

Did you find a way to update to Pillow-SIMD 8.x.x ? Thanks !

**Comment by dverheijden** [comment]
As of writing, Pillow-SIMD hasn't been updated after June 2nd 2020 (see date on 5bf26ac). The last Pillow version that Pillow-SIMD supports is `7.0.0` (see also [the PyPi versions](https://pypi.org/project/Pillow-SIMD/#history)).

**Comment by jhagege** [comment]
Thanks much for your reply.
I am wondering what would be the effort to add support for later versions ?

Any idea what are the main differences between Pillow and Pillow-SIMD repo
?
Thanks.

**Comment by homm** [comment]
Versions `7.0.0.post4`, `7.1.2.post1`, `7.2.0.post1`, `8.0.1.post0` and `8.1.2.post0` released.

**Comment by w-** [comment]
finally heh. Thank you.

**Comment by homm** [comment]
Versions `8.2.0.post0`, `8.3.2.post0` and `8.4.0.post0` released.
